[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pete_staking = "CTg35G6Cin3iQZHe8i5pN9rJ5ajSyCN2sjvDmVfCyVpi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/odmin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
